version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quant-trading-api
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www
    environment:
      - FLASK_APP=src/run.py
      - FLASK_ENV=development